#!/bin/bash
###############################################################################
# Author: Matthias Thubauville
# Last change: 2015-03-03
#
# General dynamic motd.
# Tested with:
# - Ubuntu 14.04.1
# - CentOS 7
#
# This file is meant to be put in your $PATH and run from the .profile.
# This means the output is printed with every new login shell, i.e. a TTY or
# ssh login.
###############################################################################

function get_script_path
{

# This figures out where the file is stored and saves it into $SCRIPT_PATH
# This allowes to run the source script from anywhere (you don't have to cd into the qcmine folder anymore)
local script_path="${BASH_SOURCE[0]}";
if ([ -h "${script_path}" ]) then
  while([ -h "${script_path}" ]) do script_path=`readlink "${script_path}"`; done
fi
pushd . > /dev/null
cd `dirname ${script_path}` > /dev/null
local script_path=`pwd`;
popd  > /dev/null

echo $script_path

}

find $(get_script_path)/config.d -type f -or -type l | sort | while read i; do $i; done
