#!/bin/bash
###############################################################################
# Author: Matthias Thubauville
#
# General dynamic motd.
# Tested with:
# - Ubuntu 14.04
# - Ubuntu 16.04
# - CentOS 7
#
# This file is meant to be put in your $PATH and run from the .profile.
# This means the output is printed with every new login shell, i.e. a TTY or
# ssh login.
###############################################################################

function get_script_path
{

# see https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo $DIR

}

find $(get_script_path)/config.d -type f -or -type l | sort | while read i; do $i; done
