#!/bin/bash

if [[ -f /proc/cpuinfo ]]; then

  model=$(cat /proc/cpuinfo | grep "^model name" | cut -d : -f 2 | head -n 1)
  # currfreq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq 2>/dev/null  | awk '{printf "%1.2f\n", $1/1000000 }')
  htcores=$(cat /proc/cpuinfo | grep "model name" | wc -l)
  cores=$(( $htcores / 2 ))

  echo -e "${COLOR_PURPLE}+          ${COLOR_GREEN}CPU ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}`echo 2x $model total $cores CPU-Cores / $htcores HT-Cores `"

fi
