#!/bin/bash
last_f2b=$(if [[ -e /var/log/fail2ban.log ]]; then tail -n1 /var/log/fail2ban.log || echo "Permission denied"; else echo "No Fail2ban"; fi)

echo -e "\033[0;35m+     \033[0;37mFail2ban \033[0;35m= \033[1;32m$last_f2b"
