#!/bin/bash
# last_f2b=$(if [[ -e /var/log/fail2ban.log ]]; then tail -n1 /var/log/fail2ban.log || echo "Permission denied"; else echo "No Fail2ban"; fi)

if [[ -e /var/log/fail3ban.log ]]; then
  last_f2b=$(tail -n1 /var/log/fail2ban.log || echo "Permission denied")
  echo -e "${COLOR_PURPLE}+     ${COLOR_GREEN}Fail2ban ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}$last_f2b"
fi

