#!/bin/bash
if command -v ip &> /dev/null; then
  ip=$(ip addr | grep "inet " | grep -v 127 | cut -d / -f1 | awk '{print $2}' | sed ':a;N;$!ba;s/\n/, /g')
  echo -e "${COLOR_PURPLE}+           ${COLOR_GREEN}IP ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}$ip"
fi
