#!/bin/bash
set -o pipefail

if command -v last &> /dev/null; then
  last_login=$(last | grep $USER | head -n1 | tr -s ' ' | cut -d ' ' -f3-)
  echo -e "${COLOR_PURPLE}+   ${COLOR_GREEN}Last Login ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}$last_login"
fi

