#!/bin/bash

if [[ -r /etc/redhat-release ]]; then
  while read -r i; do
    if $(grep PRETTY $i > /dev/null 2>&1); then
      release=$(cat $i | grep PRETTY | cut -d = -f2)
    else
      release=$(cat $i)
    fi
  done < <(find /etc/redhat-release -type f -or -type l)
elif [[ -r /etc/lsb-release ]]; then
  while read -r i; do
    if grep -q PRETTY $i; then
      release=$(cat $i | grep PRETTY | cut -d = -f2)
    elif grep -q DESCRIPTION $i; then
      release=$(cat $i | grep DESCRIPTION | cut -d = -f2)
    else
      release=$(cat $i)
    fi
  done < <(find /etc/lsb-release -type f)
elif type lsb_release > /dev/null 2>&1; then
  release=$(lsb_release -a 2>/dev/null | grep Description | cut -d : -f2 | sed -e 's/^[ \t]*//')
else
  release="Unidentified OS!"
fi

echo -e "\033[0;35m+           \033[0;37mOS \033[0;35m= \033[1;32m$release"
