#!/bin/bash
root_pro=$(df -Phl 2>>/dev/null | grep " /$" | awk '{print $5}' | uniq)
root_tot=$(df -Phl 2>>/dev/null | grep " /$" | awk '{print $2}' | uniq)

echo -e "${COLOR_PURPLE}+         ${COLOR_GREEN}Disk ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}`echo $root_pro used of $root_tot`"
