#!/bin/bash

counter=1

if type screen > /dev/null 2>&1; then

if [[ $(screen -ls | grep "tached" | wc -l) -ne 0 ]]; then

 screen -ls | grep "tached" | awk '{print $NF, $1}' | sed -r 's/[0-9]+\.//' | while read i; do
  echo -e "${COLOR_PURPLE}+     ${COLOR_GREEN}Screen $counter ${COLOR_PURPLE}=${COLOR_LIGHT_GREEN} $i"
  counter=$(( $counter+1 ))
 done

fi

fi

