#!/bin/bash

counter=1

if type screen > /dev/null 2>&1; then

if [[ $(screen -ls | grep "tached" | wc -l) -ne 0 ]]; then

 screen -ls | grep "tached" | awk '{print $NF, $1}' | sed -r 's/[0-9]+\.//' | while read i; do
  echo -e "\033[0;35m+     \033[0;37mScreen $counter \033[0;35m=\033[1;32m $i"
  counter=$(( $counter+1 ))
 done

fi

fi

