#!/bin/bash

counter=1

if [[ $(screen -ls | grep "tached" | wc -l) -ne 0 ]]; then

 screen -ls | grep "tached" | awk '{print $4, $1}' | sed -r 's/[0-9]+\.//' | while read i; do
  echo -e "\033[0;35m+     \033[0;37mScreen $counter \033[0;35m=\033[1;32m $i"
  counter=$(( $counter+1 ))
 done

fi

   # if [[ $(screen -ls | sed -n -r 's/\x09([0-9]+)\.([[:alnum:]]+)[[:blank:]]\(([[:alnum:]]+)\)/\2: \3/p' | wc -l) > 0 ]]; then
   # $(screen -ls | sed -n -r 's/\x09([0-9]+)\.([[:alnum:]]+)[[:blank:]]\(([[:alnum:]]+)\)/ \\033[0;35m+\\033[0;37m     \3\\033[0;35m =\\033[0;37m \\033[1;32m\2\\033[0;37m/p')
   # fi
