#!/bin/bash
# selinux=$(if type sestatus > /dev/null 2>&1; then sestatus 2>/dev/null | grep "^SELinux status" | awk '{print $NF}'; else echo "No selinux"; fi)

if type sestatus > /dev/null 2>&1; then
  selinux=$(sestatus 2>/dev/null | grep "^SELinux status" | awk '{print $NF}')
  echo -e "${COLOR_PURPLE}+      ${COLOR_GREEN}SELinux ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}$selinux"
fi

