#!/bin/bash
users=$(who -u | grep -v root | awk '{print $1}' | sort -u | wc -l)
shells=$(who -u | grep -v root | awk '{print $1}' |  wc -l)

echo -e "${COLOR_PURPLE}+ ${COLOR_GREEN}Users/Shells ${COLOR_PURPLE}= ${COLOR_LIGHT_GREEN}`echo $users/$shells`"
