#!/bin/bash
users=$(who -u | grep -v root | awk '{print $1}' | sort -u | wc -l)
shells=$(who -u | grep -v root | awk '{print $1}' |  wc -l)

echo -e "\033[0;35m+ \033[0;37mUsers/Shells \033[0;35m= \033[1;32m`echo $users/$shells`"
