#!/bin/bash

# Clear the screen
printf "\033c"

# Print the dynmotd information
echo -e "$COLOR_PURPLE++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++$COLOR_NC"
